version: '2'
services:
    mongo:
        image: mongo
        ports:
            - "27107:27017"
    app:
        build: .
        ports:
            - "3050:3000"
            - "9229:9229"
        links:
            - mongo
        environment:
            - NODE_ENV=development
            - NODE_CMD=dev
        volumes:
            - ".:/app"
            - "/app/node_modules"
